<a href="https://colab.research.google.com/github/suprabhu77/C-And-Cpp/blob/master/KNN_Car_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('/content/sample_data/Iris.csv')
dataset
# len(dataset)

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
from sklearn.model_selection import train_test_split
X=dataset.iloc[:,0:5]
y = dataset.iloc[:,5]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size =0.2)


In [ ]:
from sklearn.preprocessing import StandardScaler
Sc_X = StandardScaler()
X_train = Sc_X.fit_transform(X_train)
X_test = Sc_X.fit_transform(X_test)

In [ ]:
import math
math.sqrt(len(y_test))


5.477225575051661

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3,p=2,metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [ ]:
X_test

array([[ 1.36482834,  0.14956537, -0.58304897,  0.94512598,  1.91948971],
       [-0.09748774,  0.43000045, -1.9460206 ,  0.2829358 , -0.10102577],
       [-0.91301017, -0.27108724,  2.59721815, -1.28224097, -1.25560605],
       [ 1.1679781 ,  2.25282843, -0.35588703,  1.66751526,  1.0535545 ],
       [-1.64416821, -0.97217492,  0.77992265, -1.22204187, -1.25560605],
       [ 0.97112786,  0.85065306,  0.55276071,  1.48691794,  2.06381224],
       [-0.71615993, -0.97217492,  1.00708459, -1.34244008, -1.11128352],
       [ 0.57742738,  1.41152321,  0.09843684,  0.70432955,  0.6205869 ],
       [ 0.29621274,  1.55174074, -0.58304897,  0.76452866,  0.47626436],
       [ 0.15560543,  0.57021798, -0.58304897,  0.2829358 ,  0.33194183],
       [ 1.9272576 ,  0.57021798, -1.03737285,  1.24612151,  0.47626436],
       [-0.40682383,  0.9908706 ,  0.32559878,  0.58393134,  0.6205869 ],
       [ 0.21184836,  0.57021798, -0.58304897,  0.70432955,  0.18761929],
       [-0.32245944,  1.13108813, -0.5

In [ ]:
# y_pred = classifier.predict([[-1.64416821, -0.97217492,  0.77992265, -1.22204187, -1.25560605]])
# y_pred

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [ ]:
y_test.shape
confusion_matrix_value = confusion_matrix(y_test,y_pred)
print(confusion_matrix_value)

[[11  0  0]
 [ 0 11  2]
 [ 0  0  6]]


In [ ]:
print(accuracy_score(y_test,y_pred)*100)
print(f1_score(y_test,y_pred,average='macro')*100)

93.33333333333333
92.46031746031746


In [ ]:
import pickle 
  
# Save the trained model as a pickle string. 
saved_model = pickle.dumps(classifier) 
  
# Load the pickled model 
knn_from_pickle = pickle.loads(saved_model) 
  
# Use the loaded pickled model to make predictions 
knn_from_pickle.predict([[-1.675433, .9886657	,0.39887786655,	.2	,0.2099077635332]])

array(['Iris-versicolor'], dtype=object)